[package]
name = "rust-drawing-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.131.0"
image = "0.24.7"
vecmath = "1.0.0"